CREATE TABLE `CONTATO` (
  `ID_CONTATO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `TELEFONE` varchar(100) DEFAULT NULL,
  `ESTADOCIVIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_CONTATO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
